name: Dev
on:
  push:
    branches: main

jobs:
  flutter-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
      - name: Install Android Emulator System Image
        run: |
          sdkmanager "system-images;android-33;google_apis;x86_64"
          sdkmanager "system-images;android-27;google_apis_playstore;x86"
          sdkmanager --licenses
      - name: Add Emulator to PATH
        run: echo "${ANDROID_HOME}/emulator" >> $GITHUB_PATH
      - name: Create Android Emulator
        run: |
          echo "no" | avdmanager create avd -n pixel -k "system-images;android-33;google_apis;x86_64" -d pixel
      - name: List Available AVDs
        run: avdmanager list avd
      - name: Flutter check
        run: flutter --version
      - name: Flutter doctor
        run: flutter doctor -v
      - name: Devices
        run: flutter devices
      - name: Create pixel emulator
        run: flutter emulators --create pixel
      - name: Emulators
        run: flutter emulators
      - name: Launch emulators
        run: flutter emulators --launch flutter_emulator --cold
  dependencies:
    needs: flutter-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Install dependencies
        run: flutter pub get
      - name: Clean dependencies
        run: flutter clean
      - name: Reinstall dependencies
        run: flutter pub get
  analyze:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Flutter analyze
        run: flutter analyze
  tests:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Flutter test
        run: flutter test
  coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Flutter test
        run: flutter test --coverage
      - name: Coverage
        run: flutter pub run test_cov_console
  integration-test:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
      - name: Install Android Emulator System Image
        run: |
          sdkmanager "system-images;android-33;google_apis;x86_64"
          sdkmanager "system-images;android-27;google_apis_playstore;x86"
          sdkmanager --licenses
      - name: Add Emulator to PATH
        run: echo "${ANDROID_HOME}/emulator" >> $GITHUB_PATH
      - name: Create Android Emulator
        run: |
          echo "no" | avdmanager create avd -n pixel -k "system-images;android-33;google_apis;x86_64" -d pixel
      - name: Create pixel emulator
        run: flutter emulators --create pixel
      - name: Launch emulators
        run: flutter emulators --launch flutter_emulator --cold
      - name: Integration test running
        run: flutter test integration_test/home_test.dart
