name: Dev
on:
  push:
    branches: main

jobs:
  flutter-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Flutter check
        run: flutter --version
  dependencies:
    needs: flutter-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Install dependencies
        run: flutter pub get
      - name: Clean dependencies
        run: flutter pub get
      - name: Reinstall dependencies
        run: flutter pub get
  analyze:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Flutter analyze
        run: flutter analyze
  tests:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Flutter test
        run: flutter test
