name: Dev
on:
  push:
    branches: main

jobs:
  flutter-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Flutter check
        run: flutter --version
      - name: Flutter doctor
        run: flutter doctor -v
      - name: Print work decretory
        run: pwd
      - name: List folder
        run: ls
      - name: Create pixel emulator
        run: flutter emulators --create pixel
  dependencies:
    needs: flutter-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Install dependencies
        run: flutter pub get
      - name: Clean dependencies
        run: flutter clean
      - name: Reinstall dependencies
        run: flutter pub get
  analyze:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Flutter analyze
        run: flutter analyze
  tests:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Flutter test
        run: flutter test
  coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Flutter test
        run: flutter test --coverage
      - name: Coverage
        run: flutter pub run test_cov_console
