name: Flutter Integration Test with Free Emulator

on: push

jobs:
  integration_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Android SDK Command Line Tools
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools
          sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          sudo unzip -qq sdk-tools.zip -d /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo chmod -R 777 /usr/local/lib/android/sdk
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Install Android tools
        run: |
          source $GITHUB_ENV
          sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "emulator" "system-images;android-31;default;x86_64"

      - name: Create and Start Emulator
        run: |
          source $GITHUB_ENV
          echo "no" | avdmanager create avd -n test -k "system-images;android-31;default;x86_64" --force
          emulator -avd test -no-snapshot -no-window -gpu off -no-boot-anim &

      - name: Wait for Emulator to Boot
        run: |
          source $GITHUB_ENV
          adb devices
          adb wait-for-device
          adb shell "while [[ -z \$(getprop sys.boot_completed) ]]; do sleep 1; done;"

      - name: Unlock Emulator Screen
        run: adb shell input keyevent 82

      - name: Run Integration Tests
        env:
          DISPLAY: :99
        run: flutter test integration_test/home_test.dart
