name: Integration Test
on:
  push:
    branches:
      - main
jobs:
  integration-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: futureware-tech/simulator-action@v4
        with:
          model: "iPhone 13"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test integration_test/home_test.dart
